theme: jekyll-theme-hydeout

markdown: kramdown
highlighter: rouge

title: Allan Vital
tagline: 'I build software and stuff'
description: 'About Software Development, Problem Solving and the human side of tech. <a href="/about" target="_blank">More about me</a>.'

hydeout:
  github: https://github.com/vitallan

author:
  name: 'Allan Vital'
  url: https://twitter.com/allanvital

url: "https://allanvital.com" 

github: https://github.com/vitallan
stackoverflow: https://stackoverflow.com/users/3632899/allan-vital
twitter: https://twitter.com/allanvital
linkedin: https://www.linkedin.com/in/allanvital/

paginate: 5

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap

sidebar_home_link: true
sidebar_link: true
